[project]
name        = 'ap_utilities'
description = 'Utilities needed for analysis productions in LHCb'
version     = '0.0.4'
readme      = 'README.md'
dependencies= ['PyYAML', 'data-manipulation-utilities>=0.0.8']

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where= ['src']

[project.scripts]
check_samples ='ap_utilities_scripts.check_samples:main'

[tool.setuptools.package-data]
'ap_utilities_data' = ['*.json', '*.toml']

